services:
  # Servicio del Backend
  flask_app:
    build: ./backend
    container_name: flask_services
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - FLASK_ENV=production

  # Servicio del Frontend + Nginx
  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_frontend
    restart: always
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - flask_app
